/**
 * The criteria registry, shaped for export to the Python service.
 *
 * Pure: it builds the object and writes nothing. `scripts/export-criteria.ts`
 * imports this and writes the file; `__tests__/export-sync.test.ts` imports it
 * and compares against the committed one. Splitting them is what lets the test
 * detect a stale artifact instead of silently regenerating it, which is the
 * only way the check has any teeth.
 *
 * The TypeScript literals in this directory are the AUTHORED source and
 * `contracts/criteria.json` is the generated artifact. The alternative was a
 * hand-written second copy of every class table in Python, and the entire point
 * of the criteria work is that a slope table disagreeing with itself maps
 * landslide susceptibility upside down.
 */

import { FLOOD_DEFAULT_WEIGHTS } from "@/lib/criteria/flood";
import { criteriaFor, methodFor } from "@/lib/criteria";

/** Topics that run a weighted overlay, and therefore have criteria to export. */
export const EXPORTED_TOPICS = ["flood-risk", "landslide"] as const;

export function buildCriteriaExport() {
  return {
    $comment:
      "GENERATED by my-app/scripts/export-criteria.ts from my-app/lib/criteria. " +
      "Do not edit by hand: edit the TypeScript registry and re-run " +
      "`npx vite-node -c vitest.config.mts scripts/export-criteria.ts`. " +
      "my-app/lib/criteria/__tests__/export-sync.test.ts fails when this file is stale.",
    version: 1,
    topics: Object.fromEntries(
      EXPORTED_TOPICS.map((topic) => {
        const method = methodFor(topic);
        return [
          topic,
          {
            method: method.kind,
            criteria: criteriaFor(topic),
            defaultWeights:
              method.kind === "weighted-overlay"
                ? (method.defaultWeights ?? null)
                : null,
          },
        ];
      }),
    ),
    floodDefaultWeights: FLOOD_DEFAULT_WEIGHTS,
  };
}

/** The exact bytes the artifact should contain, so the check is byte-level. */
export function serialiseCriteriaExport(): string {
  return `${JSON.stringify(buildCriteriaExport(), null, 2)}\n`;
}
