# Generated by Django 5.2.15 on 2026-09-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('run_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('topic', models.CharField(db_index=True, max_length=64)),
                ('config', models.JSONField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=16)),
                ('stages', models.JSONField(default=list)),
                ('progress', models.FloatField(default=0.0)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('workspace', models.CharField(blank=True, default='', max_length=512)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
